#encoding: utf-8
module Core
  module Permissions
    class Ability

      include CanCan::Ability

      def initialize(user)

        can :manage, :all if user.super_user?

        can :edit, :settings_medo if user.rights.include?('settings_medo_edit')
        can :edit, :settings_reports if user.rights.include?('settings_reports_edit')
        can :edit, :settings_fields_values if user.rights.include?('settings_fields_values_edit')
        can :edit, :settings_primary_consideration if user.rights.include?('settings_primary_consideration_edit')
        can :edit, :settings_scan_folders if user.rights.include?('settings_scan_folders_edit')
        can :edit, :settings_citizen_requests_organizations if user.rights.include?('settings_citizen_requests_organizations_edit')
        can :edit, :settings_document_apply if user.rights.include?('settings_document_apply_edit')
        can :edit, :settings_control_repeat_period if user.rights.include?('settings_control_repeat_period_edit')
        can :edit, :settings_print_barcodes if user.rights.include?('settings_print_barcodes_edit')
        can :edit, :settings_journals if user.rights.include?('settings_journals_edit')
        can :edit, :settings_blocked_numbers if user.rights.include?('settings_blocked_numbers_edit')
        can :edit, :settings_providers if user.rights.include?('settings_providers_edit')
        can :edit, :settings_control_documents_type if user.rights.include?('settings_control_documents_type_edit')
        can :edit, :settings_resolution_types if user.rights.include?('settings_resolution_types_edit')
        can :edit, :settings_registration_number if user.rights.include?('settings_registration_number_edit')
        can :edit, :settings_letterhead_resolutions if user.rights.include?('settings_letterhead_resolutions_edit')
        can :edit, :settings_cover_letter_heads if user.rights.include?('settings_cover_letter_heads_edit')
        can :edit, :settings_contract_number if user.rights.include?('settings_contract_number_edit')
        can :edit, :settings_bpe_settings if user.rights.include?('settings_bpe_settings_edit')
        can :edit, :settings_orders_delivery_groups if user.rights.include?('settings_orders_delivery_groups_edit')
        can :edit, :settings_performance_control_person if user.rights.include?('settings_performance_control_person_edit')
        
        can :show, :settings_medo if user.rights.include?('settings_medo_show')
        can :show, :settings_reports if user.rights.include?('settings_reports_show')
        can :show, :settings_fields_values if user.rights.include?('settings_fields_values_show')
        can :show, :settings_primary_consideration if user.rights.include?('settings_primary_consideration_show')
        can :show, :settings_scan_folders if user.rights.include?('settings_scan_folders_show')
        can :show, :settings_citizen_requests_organizations if user.rights.include?('settings_citizen_requests_organizations_show')
        can :show, :settings_document_apply if user.rights.include?('settings_document_apply_show')
        can :show, :settings_control_repeat_period if user.rights.include?('settings_control_repeat_period_show')
        can :show, :settings_print_barcodes if user.rights.include?('settings_print_barcodes_show')
        can :show, :settings_journals if user.rights.include?('settings_journals_show')
        can :show, :settings_blocked_numbers if user.rights.include?('settings_blocked_numbers_show')
        can :show, :settings_providers if user.rights.include?('settings_providers_show')
        can :show, :settings_control_documents_type if user.rights.include?('settings_control_documents_type_show')
        can :show, :settings_resolution_types if user.rights.include?('settings_resolution_types_show')
        can :show, :settings_registration_number if user.rights.include?('settings_registration_number_show')
        can :show, :settings_letterhead_resolutions if user.rights.include?('settings_letterhead_resolutions_show')
        can :show, :settings_cover_letter_heads if user.rights.include?('settings_cover_letter_heads_show')
        can :edit, :settings_performance_control_person if user.rights.include?('settings_performance_control_person_show')

        can :from_report, :incoming_documents if user.rights.include?('incoming_documents_from_report')
        can :return_from_familiarization, :incoming_documents if user.rights.include?('incoming_documents_return_from_familiarization')
        can :from_copy, :incoming_documents if user.rights.include?('incoming_documents_from_copy')
        can :issuance_by_book, :incoming_documents if user.rights.include?('incoming_documents_issuance_by_book')
        can :addition, :incoming_documents if user.rights.include?('incoming_documents_addition')
        can :close_cusp, :incoming_documents if user.rights.include?('incoming_documents_close_cusp')
        can :to_the_file_edit, :incoming_documents if user.rights.include?('incoming_documents_to_the_file_edit')
        can :notification_card, :incoming_documents_control if user.rights.include?('incoming_documents_control_notification_card')
        can :control_form, :incoming_documents_control if user.rights.include?('incoming_documents_control_control_form')
        can :control_form_edit, :incoming_documents_control if user.rights.include?('incoming_documents_control_control_form_edit')
        can :control_form_print, :incoming_documents_control if user.rights.include?('incoming_documents_control_control_form_print')
        can :info_card_print, :incoming_documents_control if user.rights.include?('incoming_documents_control_info_card_print')
        can :on_control, :incoming_documents_control if user.rights.include?('incoming_documents_control_on_control')
        can :from_control, :incoming_documents_control if user.rights.include?('incoming_documents_control_from_control')
        can :to_familiarization, :incoming_documents if user.rights.include?('incoming_documents_to_familiarization')
        can :registration_reminder, :incoming_documents if user.rights.include?('incoming_documents_registration_reminder')
        can :cancel, :incoming_documents if user.rights.include?('incoming_documents_cancel')
        can :transfer, :incoming_documents if user.rights.include?('incoming_documents_transfer')
        can :print_to_the_copy, :incoming_documents if user.rights.include?('incoming_documents_print_to_the_copy')
        can :print, :incoming_documents_decisions if user.rights.include?('incoming_documents_print_decisions')
        can :print_search_results, :incoming_documents if user.rights.include?('incoming_documents_print_search_results')
        can :sign, :incoming_documents_decisions if user.rights.include?('incoming_documents_sign_decisions')
        can :to_the_file, :incoming_documents if user.rights.include?('incoming_documents_to_the_file')
        can :stream_scan, :incoming_documents if user.rights.include?('incoming_documents_stream_scan')
        can :check_existance_medo, :incoming_documents if user.rights.include?('incoming_documents_check_existance_medo')
        can :check_repeat, :incoming_documents if user.rights.include?('incoming_documents_check_repeat')
        can :show, :incoming_documents if user.rights.include?('incoming_documents_show')
        can :index, :incoming_documents if user.rights.include?('incoming_documents_index')
        can :grouped_docs_work, :incoming_documents if user.rights.include?('incoming_documents_grouped_docs_work')
        can :distribution, :incoming_documents if user.rights.include?('incoming_documents_distribution')
        can :distribution_show, :incoming_documents if user.rights.include?('incoming_documents_distribution_show')
        can :search, :incoming_documents if user.rights.include?('incoming_documents_advanced_search')
        can :edit, :incoming_documents if user.rights.include?('incoming_documents_edit')
        can :reg_date_num_edit, :incoming_documents if user.rights.include?('incoming_documents_reg_date_num_edit')
        can :show, :incoming_documents_decisions if user.rights.include?('incoming_documents_decisions_show')
        can :index, :incoming_documents_decisions if user.rights.include?('incoming_documents_decisions_index')
        can :edit, :incoming_documents_decisions if user.rights.include?('incoming_documents_decisions_edit')
        can :create, :incoming_documents_decisions if user.rights.include?('incoming_documents_decisions_create')
        can :destroy, :incoming_documents_decisions if user.rights.include?('incoming_documents_decisions_destroy')
        can :create, :incoming_documents if user.rights.include?('incoming_documents_create')
        can :make_links, :incoming_documents if user.rights.include?('incoming_documents_make_links')
        can :approve, :incoming_documents_decisions if user.rights.include?('incoming_documents_approve_decisions')
        can :show, :incoming_documents_document_images if user.rights.include?('incoming_documents_document_images_show')
        can :index, :incoming_documents_document_images if user.rights.include?('incoming_documents_document_images_index')
        can :edit, :incoming_documents_document_images if user.rights.include?('incoming_documents_document_images_edit')
        can :create, :incoming_documents_document_images if user.rights.include?('incoming_documents_document_images_create')
        can :destroy, :incoming_documents_document_images if user.rights.include?('incoming_documents_document_images_destroy')

        can :view, :incoming_documents_character if user.rights.include?('incoming_documents_character_view')

        can :from_report, :secret_incoming_documents if user.rights.include?('secret_incoming_documents_from_report')
        can :return_from_familiarization, :secret_incoming_documents if user.rights.include?('secret_incoming_documents_return_from_familiarization')
        can :from_copy, :secret_incoming_documents if user.rights.include?('secret_incoming_documents_from_copy')
        can :issuance_by_book, :secret_incoming_documents if user.rights.include?('secret_incoming_documents_issuance_by_book')
        can :addition, :secret_incoming_documents if user.rights.include?('secret_incoming_documents_addition')
        can :close_cusp, :secret_incoming_documents if user.rights.include?('secret_incoming_documents_close_cusp')
        can :to_the_file_edit, :secret_incoming_documents if user.rights.include?('secret_incoming_documents_to_the_file_edit')
        can :notification_card, :secret_incoming_documents_control if user.rights.include?('secret_incoming_documents_control_notification_card')
        can :control_form, :secret_incoming_documents_control if user.rights.include?('secret_incoming_documents_control_control_form')
        can :control_form_edit, :secret_incoming_documents_control if user.rights.include?('secret_incoming_documents_control_control_form_edit')
        can :control_form_print, :secret_incoming_documents_control if user.rights.include?('secret_incoming_documents_control_control_form_print')
        can :info_card_print, :secret_incoming_documents_control if user.rights.include?('secret_incoming_documents_control_info_card_print')
        can :on_control, :secret_incoming_documents_control if user.rights.include?('secret_incoming_documents_control_on_control')
        can :from_control, :secret_incoming_documents_control if user.rights.include?('secret_incoming_documents_control_from_control')
        can :to_familiarization, :secret_incoming_documents if user.rights.include?('secret_incoming_documents_to_familiarization')
        can :registration_reminder, :secret_incoming_documents if user.rights.include?('secret_incoming_documents_registration_reminder')
        can :cancel, :secret_incoming_documents if user.rights.include?('secret_incoming_documents_cancel')
        can :transfer, :secret_incoming_documents if user.rights.include?('secret_incoming_documents_transfer')
        can :print_to_the_copy, :secret_incoming_documents if user.rights.include?('secret_incoming_documents_print_to_the_copy')
        can :print, :secret_incoming_documents__decisions if user.rights.include?('secret_incoming_documents_print_decisions')
        can :print_search_results, :secret_incoming_documents if user.rights.include?('secret_incoming_documents_print_search_results')
        can :sign, :secret_incoming_documents__decisions if user.rights.include?('secret_incoming_documents_sign_decisions')
        can :to_the_file, :secret_incoming_documents if user.rights.include?('secret_incoming_documents_to_the_file')
        can :stream_scan, :secret_incoming_documents if user.rights.include?('secret_incoming_documents_stream_scan')
        can :check_existance_medo, :secret_incoming_documents if user.rights.include?('secret_incoming_documents_check_existance_medo')
        can :check_repeat, :secret_incoming_documents if user.rights.include?('secret_incoming_documents_check_repeat')
        can :show, :secret_incoming_documents if user.rights.include?('secret_incoming_documents_show')
        can :index, :secret_incoming_documents if user.rights.include?('secret_incoming_documents_index')
        can :grouped_docs_work, :secret_incoming_documents if user.rights.include?('secret_incoming_documents_grouped_docs_work')
        can :distribution, :secret_incoming_documents if user.rights.include?('secret_incoming_documents_distribution')
        can :distribution_show, :secret_incoming_documents if user.rights.include?('secret_incoming_documents_distribution_show')
        can :search, :secret_incoming_documents if user.rights.include?('secret_incoming_documents_advanced_search')
        can :edit, :secret_incoming_documents if user.rights.include?('secret_incoming_documents_edit')
        can :reg_date_num_edit, :secret_incoming_documents if user.rights.include?('secret_incoming_documents_reg_date_num_edit')
        can :show, :secret_incoming_documents_decisions if user.rights.include?('secret_incoming_documents_decisions_show')
        can :index, :secret_incoming_documents_decisions if user.rights.include?('secret_incoming_documents_decisions_index')
        can :edit, :secret_incoming_documents_decisions if user.rights.include?('secret_incoming_documents_decisions_edit')
        can :create, :secret_incoming_documents_decisions if user.rights.include?('secret_incoming_documents_decisions_create')
        can :destroy, :secret_incoming_documents_decisions if user.rights.include?('secret_incoming_documents_decisions_destroy')
        can :create, :secret_incoming_documents if user.rights.include?('secret_incoming_documents_create')
        can :make_links, :secret_incoming_documents if user.rights.include?('secret_incoming_documents_make_links')
        can :approve, :secret_incoming_documents_decisions if user.rights.include?('secret_incoming_documents_approve_decisions')
        can :show, :secret_incoming_documents_document_images if user.rights.include?('secret_incoming_documents_document_images_show')
        can :index, :secret_incoming_documents_document_images if user.rights.include?('secret_incoming_documents_document_images_index')
        can :edit, :secret_incoming_documents_document_images if user.rights.include?('secret_incoming_documents_document_images_edit')
        can :create, :secret_incoming_documents_document_images if user.rights.include?('secret_incoming_documents_document_images_create')
        can :destroy, :secret_incoming_documents_document_images if user.rights.include?('secret_incoming_documents_document_images_destroy')

        can :show, :groups if user.rights.include?('groups_show')
        can :index, :groups if user.rights.include?('groups_index')
        can :edit, :groups if user.rights.include?('groups_edit')
        can :create, :groups if user.rights.include?('groups_create')
        can :destroy, :groups if user.rights.include?('groups_destroy')

        can :from_report, :attorney_letters if user.rights.include?('attorney_letters_from_report')
        can :return_from_familiarization, :attorney_letters if user.rights.include?('attorney_letters_return_from_familiarization')
        can :from_copy, :attorney_letters if user.rights.include?('attorney_letters_from_copy')
        can :issuance_by_book, :attorney_letters if user.rights.include?('attorney_letters_issuance_by_book')
        can :addition, :attorney_letters if user.rights.include?('attorney_letters_addition')
        can :close_cusp, :attorney_letters if user.rights.include?('attorney_letters_close_cusp')
        can :to_the_file_edit, :attorney_letters if user.rights.include?('attorney_letters_to_the_file_edit')
        can :notification_card, :attorney_letters_control if user.rights.include?('attorney_letters_control_notification_card')
        can :control_form, :attorney_letters_control if user.rights.include?('attorney_letters_control_control_form')
        can :control_form_edit, :attorney_letters_control if user.rights.include?('attorney_letters_control_control_form_edit')
        can :control_form_print, :attorney_letters_control if user.rights.include?('attorney_letters_control_control_form_print')
        can :info_card_print, :attorney_letters_control if user.rights.include?('attorney_letters_control_info_card_print')
        can :on_control, :attorney_letters_control if user.rights.include?('attorney_letters_control_on_control')
        can :from_control, :attorney_letters_control if user.rights.include?('attorney_letters_control_from_control')
        can :to_familiarization, :attorney_letters if user.rights.include?('attorney_letters_to_familiarization')
        can :registration_reminder, :attorney_letters if user.rights.include?('attorney_letters_registration_reminder')
        can :cancel, :attorney_letters if user.rights.include?('attorney_letters_cancel')
        can :transfer, :attorney_letters if user.rights.include?('attorney_letters_transfer')
        can :print_to_the_copy, :attorney_letters if user.rights.include?('attorney_letters_print_to_the_copy')
        can :print, :attorney_letters_decisions if user.rights.include?('attorney_letters_print_decisions')
        can :print_search_results, :attorney_letters if user.rights.include?('attorney_letters_print_search_results')
        can :sign, :attorney_letters_decisions if user.rights.include?('attorney_letters_sign_decisions')
        can :to_the_file, :attorney_letters if user.rights.include?('attorney_letters_to_the_file')
        can :stream_scan, :attorney_letters if user.rights.include?('attorney_letters_stream_scan')
        can :check_existance_medo, :attorney_letters if user.rights.include?('attorney_letters_check_existance_medo')
        can :check_repeat, :attorney_letters if user.rights.include?('attorney_letters_check_repeat')
        can :show, :attorney_letters if user.rights.include?('attorney_letters_show')
        can :index, :attorney_letters if user.rights.include?('attorney_letters_index')
        can :grouped_docs_work, :attorney_letters if user.rights.include?('attorney_letters_grouped_docs_work')
        can :distribution, :attorney_letters if user.rights.include?('attorney_letters_distribution')
        can :distribution_show, :attorney_letters if user.rights.include?('attorney_letters_distribution_show')
        can :search, :attorney_letters if user.rights.include?('attorney_letters_advanced_search')
        can :edit, :attorney_letters if user.rights.include?('attorney_letters_edit')
        can :reg_date_num_edit, :attorney_letters if user.rights.include?('attorney_letters_reg_date_num_edit')
        can :show, :attorney_letters_decisions if user.rights.include?('attorney_letters_decisions_show')
        can :index, :attorney_letters_decisions if user.rights.include?('attorney_letters_decisions_index')
        can :edit, :attorney_letters_decisions if user.rights.include?('attorney_letters_decisions_edit')
        can :create, :attorney_letters_decisions if user.rights.include?('attorney_letters_decisions_create')
        can :destroy, :attorney_letters_decisions if user.rights.include?('attorney_letters_decisions_destroy')
        can :create, :attorney_letters if user.rights.include?('attorney_letters_create')
        can :make_links, :attorney_letters if user.rights.include?('attorney_letters_make_links')
        can :approve, :attorney_letters_decisions if user.rights.include?('attorney_letters_approve_decisions')
        can :show, :attorney_letters_document_images if user.rights.include?('attorney_letters_document_images_show')
        can :index, :attorney_letters_document_images if user.rights.include?('attorney_letters_document_images_index')
        can :edit, :attorney_letters_document_images if user.rights.include?('attorney_letters_document_images_edit')
        can :create, :attorney_letters_document_images if user.rights.include?('attorney_letters_document_images_create')
        can :destroy, :attorney_letters_document_images if user.rights.include?('attorney_letters_document_images_destroy')

        can :refusal, :medo if user.rights.include?('medo_refusal')
        can :index, :medo if user.rights.include?('medo_index')
        can :registrate, :medo if user.rights.include?('medo_registration')

        can :access, :logs_logs if user.rights.include?('logs_logs_access')
        can :access, :logs_changes if user.rights.include?('logs_changes_access')

        can :from_report, :outgoing_documents if user.rights.include?('outgoing_documents_from_report')
        can :return_from_familiarization, :outgoing_documents if user.rights.include?('outgoing_documents_return_from_familiarization')
        can :from_copy, :outgoing_documents if user.rights.include?('outgoing_documents_from_copy')
        can :issuance_by_book, :outgoing_documents if user.rights.include?('outgoing_documents_issuance_by_book')
        can :addition, :outgoing_documents if user.rights.include?('outgoing_documents_addition')
        can :close_cusp, :outgoing_documents if user.rights.include?('outgoing_documents_close_cusp')
        can :to_the_file_edit, :outgoing_documents if user.rights.include?('outgoing_documents_to_the_file_edit')
        can :notification_card, :outgoing_documents_control if user.rights.include?('outgoing_documents_control_notification_card')
        can :control_form, :outgoing_documents_control if user.rights.include?('outgoing_documents_control_control_form')
        can :control_form_edit, :outgoing_documents_control if user.rights.include?('outgoing_documents_control_control_form_edit')
        can :control_form_print, :outgoing_documents_control if user.rights.include?('outgoing_documents_control_control_form_print')
        can :info_card_print, :outgoing_documents_control if user.rights.include?('outgoing_documents_control_info_card_print')
        can :on_control, :outgoing_documents_control if user.rights.include?('outgoing_documents_control_on_control')
        can :from_control, :outgoing_documents_control if user.rights.include?('outgoing_documents_control_from_control')
        can :to_familiarization, :outgoing_documents if user.rights.include?('outgoing_documents_to_familiarization')
        can :registration_reminder, :outgoing_documents if user.rights.include?('outgoing_documents_registration_reminder')
        can :cancel, :outgoing_documents if user.rights.include?('outgoing_documents_cancel')
        can :transfer, :outgoing_documents if user.rights.include?('outgoing_documents_transfer')
        can :print_to_the_copy, :outgoing_documents if user.rights.include?('outgoing_documents_print_to_the_copy')
        can :print, :outgoing_documents_decisions if user.rights.include?('outgoing_documents_print_decisions')
        can :print_search_results, :outgoing_documents if user.rights.include?('outgoing_documents_print_search_results')
        can :sign, :outgoing_documents_decisions if user.rights.include?('outgoing_documents_sign_decisions')
        can :to_the_file, :outgoing_documents if user.rights.include?('outgoing_documents_to_the_file')
        can :stream_scan, :outgoing_documents if user.rights.include?('outgoing_documents_stream_scan')
        can :check_existance_medo, :outgoing_documents if user.rights.include?('outgoing_documents_check_existance_medo')
        can :check_repeat, :outgoing_documents if user.rights.include?('outgoing_documents_check_repeat')
        can :show, :outgoing_documents if user.rights.include?('outgoing_documents_show')
        can :index, :outgoing_documents if user.rights.include?('outgoing_documents_index')
        can :grouped_docs_work, :outgoing_documents if user.rights.include?('outgoing_documents_grouped_docs_work')
        can :distribution, :outgoing_documents if user.rights.include?('outgoing_documents_distribution')
        can :distribution_show, :outgoing_documents if user.rights.include?('outgoing_documents_distribution_show')
        can :search, :outgoing_documents if user.rights.include?('outgoing_documents_advanced_search')
        can :edit, :outgoing_documents if user.rights.include?('outgoing_documents_edit')
        can :reg_date_num_edit, :outgoing_documents if user.rights.include?('outgoing_documents_reg_date_num_edit')
        can :show, :outgoing_documents_decisions if user.rights.include?('outgoing_documents_decisions_show')
        can :index, :outgoing_documents_decisions if user.rights.include?('outgoing_documents_decisions_index')
        can :edit, :outgoing_documents_decisions if user.rights.include?('outgoing_documents_decisions_edit')
        can :create, :outgoing_documents_decisions if user.rights.include?('outgoing_documents_decisions_create')
        can :destroy, :outgoing_documents_decisions if user.rights.include?('outgoing_documents_decisions_destroy')
        can :create, :outgoing_documents if user.rights.include?('outgoing_documents_create')
        can :make_links, :outgoing_documents if user.rights.include?('outgoing_documents_make_links')
        can :approve, :outgoing_documents_decisions if user.rights.include?('outgoing_documents_approve_decisions')
        can :show, :outgoing_documents_document_images if user.rights.include?('outgoing_documents_document_images_show')
        can :index, :outgoing_documents_document_images if user.rights.include?('outgoing_documents_document_images_index')
        can :edit, :outgoing_documents_document_images if user.rights.include?('outgoing_documents_document_images_edit')
        can :create, :outgoing_documents_document_images if user.rights.include?('outgoing_documents_document_images_create')
        can :destroy, :outgoing_documents_document_images if user.rights.include?('outgoing_documents_document_images_destroy')

        can :from_report, :secret_outgoing_documents if user.rights.include?('secret_outgoing_documents_from_report')
        can :return_from_familiarization, :secret_outgoing_documents if user.rights.include?('secret_outgoing_documents_return_from_familiarization')
        can :from_copy, :secret_outgoing_documents if user.rights.include?('secret_outgoing_documents_from_copy')
        can :issuance_by_book, :secret_outgoing_documents if user.rights.include?('secret_outgoing_documents_issuance_by_book')
        can :addition, :secret_outgoing_documents if user.rights.include?('secret_outgoing_documents_addition')
        can :close_cusp, :secret_outgoing_documents if user.rights.include?('secret_outgoing_documents_close_cusp')
        can :to_the_file_edit, :secret_outgoing_documents if user.rights.include?('secret_outgoing_documents_to_the_file_edit')
        can :notification_card, :secret_outgoing_documents_control if user.rights.include?('secret_outgoing_documents_control_notification_card')
        can :control_form, :secret_outgoing_documents_control if user.rights.include?('secret_outgoing_documents_control_control_form')
        can :control_form_edit, :secret_outgoing_documents_control if user.rights.include?('secret_outgoing_documents_control_control_form_edit')
        can :control_form_print, :secret_outgoing_documents_control if user.rights.include?('secret_outgoing_documents_control_control_form_print')
        can :info_card_print, :secret_outgoing_documents_control if user.rights.include?('secret_outgoing_documents_control_info_card_print')
        can :on_control, :secret_outgoing_documents_control if user.rights.include?('secret_outgoing_documents_control_on_control')
        can :from_control, :secret_outgoing_documents_control if user.rights.include?('secret_outgoing_documents_control_from_control')
        can :to_familiarization, :secret_outgoing_documents if user.rights.include?('secret_outgoing_documents_to_familiarization')
        can :registration_reminder, :secret_outgoing_documents if user.rights.include?('secret_outgoing_documents_registration_reminder')
        can :cancel, :secret_outgoing_documents if user.rights.include?('secret_outgoing_documents_cancel')
        can :transfer, :secret_outgoing_documents if user.rights.include?('secret_outgoing_documents_transfer')
        can :print_to_the_copy, :secret_outgoing_documents if user.rights.include?('secret_outgoing_documents_print_to_the_copy')
        can :print, :secret_outgoing_documents_decisions if user.rights.include?('secret_outgoing_documents_print_decisions')
        can :print_search_results, :secret_outgoing_documents if user.rights.include?('secret_outgoing_documents_print_search_results')
        can :sign, :secret_outgoing_documents_decisions if user.rights.include?('secret_outgoing_documents_sign_decisions')
        can :to_the_file, :secret_outgoing_documents if user.rights.include?('secret_outgoing_documents_to_the_file')
        can :stream_scan, :secret_outgoing_documents if user.rights.include?('secret_outgoing_documents_stream_scan')
        can :check_existance_medo, :secret_outgoing_documents if user.rights.include?('secret_outgoing_documents_check_existance_medo')
        can :check_repeat, :secret_outgoing_documents if user.rights.include?('secret_outgoing_documents_check_repeat')
        can :show, :secret_outgoing_documents if user.rights.include?('secret_outgoing_documents_show')
        can :index, :secret_outgoing_documents if user.rights.include?('secret_outgoing_documents_index')
        can :grouped_docs_work, :secret_outgoing_documents if user.rights.include?('secret_outgoing_documents_grouped_docs_work')
        can :distribution, :secret_outgoing_documents if user.rights.include?('secret_outgoing_documents_distribution')
        can :distribution_show, :secret_outgoing_documents if user.rights.include?('secret_outgoing_documents_distribution_show')
        can :search, :secret_outgoing_documents if user.rights.include?('secret_outgoing_documents_advanced_search')
        can :edit, :secret_outgoing_documents if user.rights.include?('secret_outgoing_documents_edit')
        can :reg_date_num_edit, :secret_outgoing_documents if user.rights.include?('secret_outgoing_documents_reg_date_num_edit')
        can :show, :secret_outgoing_documents_decisions if user.rights.include?('secret_outgoing_documents_decisions_show')
        can :index, :secret_outgoing_documents_decisions if user.rights.include?('secret_outgoing_documents_decisions_index')
        can :edit, :secret_outgoing_documents_decisions if user.rights.include?('secret_outgoing_documents_decisions_edit')
        can :create, :secret_outgoing_documents_decisions if user.rights.include?('secret_outgoing_documents_decisions_create')
        can :destroy, :secret_outgoing_documents_decisions if user.rights.include?('secret_outgoing_documents_decisions_destroy')
        can :create, :secret_outgoing_documents if user.rights.include?('secret_outgoing_documents_create')
        can :make_links, :secret_outgoing_documents if user.rights.include?('secret_outgoing_documents_make_links')
        can :approve, :secret_outgoing_documents_decisions if user.rights.include?('secret_outgoing_documents_approve_decisions')
        can :show, :secret_outgoing_documents_document_images if user.rights.include?('secret_outgoing_documents_document_images_show')
        can :index, :secret_outgoing_documents_document_images if user.rights.include?('secret_outgoing_documents_document_images_index')
        can :edit, :secret_outgoing_documents_document_images if user.rights.include?('secret_outgoing_documents_document_images_edit')
        can :create, :secret_outgoing_documents_document_images if user.rights.include?('secret_outgoing_documents_document_images_create')
        can :destroy, :secret_outgoing_documents_document_images if user.rights.include?('secret_outgoing_documents_document_images_destroy')

        can :view_expiring_docs, :control if user.rights.include?('control_view_expiring_docs')
        can :view_control_docs, :control if user.rights.include?('control_view_control_docs')
        can :view_control_docs_for_today, :control if user.rights.include?('control_view_control_docs_for_today')
        can :view_overdue_docs, :control if user.rights.include?('control_view_overdue_docs')
        can :view_from_control_docs, :control if user.rights.include?('control_view_from_control_docs')

        can :from_report, :secret_incoming_orders if user.rights.include?('secret_incoming_orders_from_report')
        can :return_from_familiarization, :secret_incoming_orders if user.rights.include?('secret_incoming_orders_return_from_familiarization')
        can :from_copy, :secret_incoming_orders if user.rights.include?('secret_incoming_orders_from_copy')
        can :issuance_by_book, :secret_incoming_orders if user.rights.include?('secret_incoming_orders_issuance_by_book')
        can :addition, :secret_incoming_orders if user.rights.include?('secret_incoming_orders_addition')
        can :close_cusp, :secret_incoming_orders if user.rights.include?('secret_incoming_orders_close_cusp')
        can :to_the_file_edit, :secret_incoming_orders if user.rights.include?('secret_incoming_orders_to_the_file_edit')
        can :notification_card, :secret_incoming_orders_control if user.rights.include?('secret_incoming_orders_control_notification_card')
        can :control_form, :secret_incoming_orders_control if user.rights.include?('secret_incoming_orders_control_control_form')
        can :control_form_edit, :secret_incoming_orders_control if user.rights.include?('secret_incoming_orders_control_control_form_edit')
        can :control_form_print, :secret_incoming_orders_control if user.rights.include?('secret_incoming_orders_control_control_form_print')
        can :info_card_print, :secret_incoming_orders_control if user.rights.include?('secret_incoming_orders_control_info_card_print')
        can :on_control, :secret_incoming_orders_control if user.rights.include?('secret_incoming_orders_control_on_control')
        can :from_control, :secret_incoming_orders_control if user.rights.include?('secret_incoming_orders_control_from_control')
        can :to_familiarization, :secret_incoming_orders if user.rights.include?('secret_incoming_orders_to_familiarization')
        can :registration_reminder, :secret_incoming_orders if user.rights.include?('secret_incoming_orders_registration_reminder')
        can :cancel, :secret_incoming_orders if user.rights.include?('secret_incoming_orders_cancel')
        can :transfer, :secret_incoming_orders if user.rights.include?('secret_incoming_orders_transfer')
        can :print_to_the_copy, :secret_incoming_orders if user.rights.include?('secret_incoming_orders_print_to_the_copy')
        can :print, :secret_incoming_orders_decisions if user.rights.include?('secret_incoming_orders_print_decisions')
        can :print_search_results, :secret_incoming_orders if user.rights.include?('secret_incoming_orders_print_search_results')
        can :sign, :secret_incoming_orders_decisions if user.rights.include?('secret_incoming_orders_sign_decisions')
        can :to_the_file, :secret_incoming_orders if user.rights.include?('secret_incoming_orders_to_the_file')
        can :stream_scan, :secret_incoming_orders if user.rights.include?('secret_incoming_orders_stream_scan')
        can :check_existance_medo, :secret_incoming_orders if user.rights.include?('secret_incoming_orders_check_existance_medo')
        can :check_repeat, :secret_incoming_orders if user.rights.include?('secret_incoming_orders_check_repeat')
        can :show, :secret_incoming_orders if user.rights.include?('secret_incoming_orders_show')
        can :index, :secret_incoming_orders if user.rights.include?('secret_incoming_orders_index')
        can :grouped_docs_work, :secret_incoming_orders if user.rights.include?('secret_incoming_orders_grouped_docs_work')
        can :distribution, :secret_incoming_orders if user.rights.include?('secret_incoming_orders_distribution')
        can :distribution_show, :secret_incoming_orders if user.rights.include?('secret_incoming_orders_distribution_show')
        can :search, :secret_incoming_orders if user.rights.include?('secret_incoming_orders_advanced_search')
        can :edit, :secret_incoming_orders if user.rights.include?('secret_incoming_orders_edit')
        can :reg_date_num_edit, :secret_incoming_orders if user.rights.include?('secret_incoming_orders_reg_date_num_edit')
        can :show, :secret_incoming_orders_decisions if user.rights.include?('secret_incoming_orders_decisions_show')
        can :index, :secret_incoming_orders_decisions if user.rights.include?('secret_incoming_orders_decisions_index')
        can :edit, :secret_incoming_orders_decisions if user.rights.include?('secret_incoming_orders_decisions_edit')
        can :create, :secret_incoming_orders_decisions if user.rights.include?('secret_incoming_orders_decisions_create')
        can :destroy, :secret_incoming_orders_decisions if user.rights.include?('secret_incoming_orders_decisions_destroy')
        can :create, :secret_incoming_orders if user.rights.include?('secret_incoming_orders_create')
        can :make_links, :secret_incoming_orders if user.rights.include?('secret_incoming_orders_make_links')
        can :approve, :secret_incoming_orders_decisions if user.rights.include?('secret_incoming_orders_approve_decisions')
        can :show, :secret_incoming_orders_document_images if user.rights.include?('secret_incoming_orders_document_images_show')
        can :index, :secret_incoming_orders_document_images if user.rights.include?('secret_incoming_orders_document_images_index')
        can :edit, :secret_incoming_orders_document_images if user.rights.include?('secret_incoming_orders_document_images_edit')
        can :create, :secret_incoming_orders_document_images if user.rights.include?('secret_incoming_orders_document_images_create')
        can :destroy, :secret_incoming_orders_document_images if user.rights.include?('secret_incoming_orders_document_images_destroy')

        can :from_report, :incoming_orders if user.rights.include?('incoming_orders_from_report')
        can :return_from_familiarization, :incoming_orders if user.rights.include?('incoming_orders_return_from_familiarization')
        can :from_copy, :incoming_orders if user.rights.include?('incoming_orders_from_copy')
        can :issuance_by_book, :incoming_orders if user.rights.include?('incoming_orders_issuance_by_book')
        can :addition, :incoming_orders if user.rights.include?('incoming_orders_addition')
        can :close_cusp, :incoming_orders if user.rights.include?('incoming_orders_close_cusp')
        can :to_the_file_edit, :incoming_orders if user.rights.include?('incoming_orders_to_the_file_edit')
        can :notification_card, :incoming_orders_control if user.rights.include?('incoming_orders_control_notification_card')
        can :control_form, :incoming_orders_control if user.rights.include?('incoming_orders_control_control_form')
        can :control_form_edit, :incoming_orders_control if user.rights.include?('incoming_orders_control_control_form_edit')
        can :control_form_print, :incoming_orders_control if user.rights.include?('incoming_orders_control_control_form_print')
        can :info_card_print, :incoming_orders_control if user.rights.include?('incoming_orders_control_info_card_print')
        can :on_control, :incoming_orders_control if user.rights.include?('incoming_orders_control_on_control')
        can :from_control, :incoming_orders_control if user.rights.include?('incoming_orders_control_from_control')
        can :to_familiarization, :incoming_orders if user.rights.include?('incoming_orders_to_familiarization')
        can :registration_reminder, :incoming_orders if user.rights.include?('incoming_orders_registration_reminder')
        can :cancel, :incoming_orders if user.rights.include?('incoming_orders_cancel')
        can :transfer, :incoming_orders if user.rights.include?('incoming_orders_transfer')
        can :print_to_the_copy, :incoming_orders if user.rights.include?('incoming_orders_print_to_the_copy')
        can :print, :incoming_orders_decisions if user.rights.include?('incoming_orders_print_decisions')
        can :print_search_results, :incoming_orders if user.rights.include?('incoming_orders_print_search_results')
        can :sign, :incoming_orders_decisions if user.rights.include?('incoming_orders_sign_decisions')
        can :to_the_file, :incoming_orders if user.rights.include?('incoming_orders_to_the_file')
        can :stream_scan, :incoming_orders if user.rights.include?('incoming_orders_stream_scan')
        can :check_existance_medo, :incoming_orders if user.rights.include?('incoming_orders_check_existance_medo')
        can :check_repeat, :incoming_orders if user.rights.include?('incoming_orders_check_repeat')
        can :show, :incoming_orders if user.rights.include?('incoming_orders_show')
        can :index, :incoming_orders if user.rights.include?('incoming_orders_index')
        can :grouped_docs_work, :incoming_orders if user.rights.include?('incoming_orders_grouped_docs_work')
        can :distribution, :incoming_orders if user.rights.include?('incoming_orders_distribution')
        can :distribution_show, :incoming_orders if user.rights.include?('incoming_orders_distribution_show')
        can :search, :incoming_orders if user.rights.include?('incoming_orders_advanced_search')
        can :edit, :incoming_orders if user.rights.include?('incoming_orders_edit')
        can :reg_date_num_edit, :incoming_orders if user.rights.include?('incoming_orders_reg_date_num_edit')
        can :show, :incoming_orders_decisions if user.rights.include?('incoming_orders_decisions_show')
        can :index, :incoming_orders_decisions if user.rights.include?('incoming_orders_decisions_index')
        can :edit, :incoming_orders_decisions if user.rights.include?('incoming_orders_decisions_edit')
        can :create, :incoming_orders_decisions if user.rights.include?('incoming_orders_decisions_create')
        can :destroy, :incoming_orders_decisions if user.rights.include?('incoming_orders_decisions_destroy')
        can :create, :incoming_orders if user.rights.include?('incoming_orders_create')
        can :make_links, :incoming_orders if user.rights.include?('incoming_orders_make_links')
        can :approve, :incoming_orders_decisions if user.rights.include?('incoming_orders_approve_decisions')
        can :show, :incoming_orders_document_images if user.rights.include?('incoming_orders_document_images_show')
        can :index, :incoming_orders_document_images if user.rights.include?('incoming_orders_document_images_index')
        can :edit, :incoming_orders_document_images if user.rights.include?('incoming_orders_document_images_edit')
        can :create, :incoming_orders_document_images if user.rights.include?('incoming_orders_document_images_create')
        can :destroy, :incoming_orders_document_images if user.rights.include?('incoming_orders_document_images_destroy')

        can :show, :oshs_mvd_positions if user.rights.include?('oshs_mvd_positions_show')
        can :index, :oshs_mvd_positions if user.rights.include?('oshs_mvd_positions_index')
        can :edit, :oshs_mvd_positions if user.rights.include?('oshs_mvd_positions_edit')
        can :create, :oshs_mvd_positions if user.rights.include?('oshs_mvd_positions_create')
        can :destroy, :oshs_mvd_positions if user.rights.include?('oshs_mvd_positions_destroy')
        can :show, :oshs_mvd_officials if user.rights.include?('oshs_mvd_officials_show')
        can :index, :oshs_mvd_officials if user.rights.include?('oshs_mvd_officials_index')
        can :edit, :oshs_mvd_officials if user.rights.include?('oshs_mvd_officials_edit')
        can :create, :oshs_mvd_officials if user.rights.include?('oshs_mvd_officials_create')
        can :destroy, :oshs_mvd_officials if user.rights.include?('oshs_mvd_officials_destroy')
        can :show, :oshs_mvd_organizations if user.rights.include?('oshs_mvd_organizations_show')
        can :index, :oshs_mvd_organizations if user.rights.include?('oshs_mvd_organizations_index')
        can :edit, :oshs_mvd_organizations if user.rights.include?('oshs_mvd_organizations_edit')
        can :create, :oshs_mvd_organizations if user.rights.include?('oshs_mvd_organizations_create')
        can :destroy, :oshs_mvd_organizations if user.rights.include?('oshs_mvd_organizations_destroy')

        can :show, :oshs_esd_positions if user.rights.include?('oshs_esd_positions_show')
        can :index, :oshs_esd_positions if user.rights.include?('oshs_esd_positions_index')
        can :edit, :oshs_esd_positions if user.rights.include?('oshs_esd_positions_edit')
        can :create, :oshs_esd_positions if user.rights.include?('oshs_esd_positions_create')
        can :destroy, :oshs_esd_positions if user.rights.include?('oshs_esd_positions_destroy')
        can :show, :oshs_esd_officials if user.rights.include?('oshs_esd_officials_show')
        can :index, :oshs_esd_officials if user.rights.include?('oshs_esd_officials_index')
        can :edit, :oshs_esd_officials if user.rights.include?('oshs_esd_officials_edit')
        can :create, :oshs_esd_officials if user.rights.include?('oshs_esd_officials_create')
        can :destroy, :oshs_esd_officials if user.rights.include?('oshs_esd_officials_destroy')
        can :show, :oshs_esd_organizations if user.rights.include?('oshs_esd_organizations_show')
        can :index, :oshs_esd_organizations if user.rights.include?('oshs_esd_organizations_index')
        can :edit, :oshs_esd_organizations if user.rights.include?('oshs_esd_organizations_edit')
        can :create, :oshs_esd_organizations if user.rights.include?('oshs_esd_organizations_create')
        can :destroy, :oshs_esd_organizations if user.rights.include?('oshs_esd_organizations_destroy')

        can :from_report, :citizen_requests if user.rights.include?('citizen_requests_from_report')
        can :return_from_familiarization, :citizen_requests if user.rights.include?('citizen_requests_return_from_familiarization')
        can :from_copy, :citizen_requests if user.rights.include?('citizen_requests_from_copy')
        can :issuance_by_book, :citizen_requests if user.rights.include?('citizen_requests_issuance_by_book')
        can :addition, :citizen_requests if user.rights.include?('citizen_requests_addition')
        can :close_cusp, :citizen_requests if user.rights.include?('citizen_requests_close_cusp')
        can :to_the_file_edit, :citizen_requests if user.rights.include?('citizen_requests_to_the_file_edit')
        can :notification_card, :citizen_requests_control if user.rights.include?('citizen_requests_control_notification_card')
        can :control_form, :citizen_requests_control if user.rights.include?('citizen_requests_control_control_form')
        can :control_form_edit, :citizen_requests_control if user.rights.include?('citizen_requests_control_control_form_edit')
        can :control_form_print, :citizen_requests_control if user.rights.include?('citizen_requests_control_control_form_print')
        can :info_card_print, :citizen_requests_control if user.rights.include?('citizen_requests_control_info_card_print')
        can :on_control, :citizen_requests_control if user.rights.include?('citizen_requests_control_on_control')
        can :from_control, :citizen_requests_control if user.rights.include?('citizen_requests_control_from_control')
        can :to_familiarization, :citizen_requests if user.rights.include?('citizen_requests_to_familiarization')
        can :registration_reminder, :citizen_requests if user.rights.include?('citizen_requests_registration_reminder')
        can :cancel, :citizen_requests if user.rights.include?('citizen_requests_cancel')
        can :view_delete_all_button, :citizen_requests if user.rights.include?('citizen_requests_view_delete_all_button')
        can :transfer, :citizen_requests if user.rights.include?('citizen_requests_transfer')
        can :print_to_the_copy, :citizen_requests if user.rights.include?('citizen_requests_print_to_the_copy')
        can :print, :citizen_requests_decisions if user.rights.include?('citizen_requests_print_decisions')
        can :print_search_results, :citizen_requests if user.rights.include?('citizen_requests_print_search_results')
        can :sign, :citizen_requests_decisions if user.rights.include?('citizen_requests_sign_decisions')
        can :to_the_file, :citizen_requests if user.rights.include?('citizen_requests_to_the_file')
        can :stream_scan, :citizen_requests if user.rights.include?('citizen_requests_stream_scan')
        can :mvd_create, :citizen_requests if user.rights.include?('citizen_requests_mvd_create')
        can :mvd_create_and_edit, :citizen_requests if user.rights.include?('citizen_requests_mvd_create_and_edit')
        can :mvd_create_repeat, :citizen_requests if user.rights.include?('citizen_requests_mvd_create_repeat')
        can :mvd_destroy_union, :citizen_requests if user.rights.include?('citizen_requests_mvd_destroy_union')
        can :check_existance_medo, :citizen_requests if user.rights.include?('citizen_requests_check_existance_medo')
        can :check_repeat, :citizen_requests if user.rights.include?('citizen_requests_check_repeat')
        can :show, :citizen_requests if user.rights.include?('citizen_requests_show')
        can :index, :citizen_requests if user.rights.include?('citizen_requests_index')
        can :grouped_docs_work, :citizen_requests if user.rights.include?('citizen_requests_grouped_docs_work')
        can :distribution_show, :citizen_requests if user.rights.include?('citizen_requests_distribution_show')
        can :search, :citizen_requests if user.rights.include?('citizen_requests_advanced_search')
        can :edit, :citizen_requests if user.rights.include?('citizen_requests_edit')
        can :primary_consideration_edit, :citizen_requests if user.rights.include?('citizen_requests_primary_consideration_edit')
        can :registration_edit, :citizen_requests if user.rights.include?('citizen_requests_registration_edit')
        can :reg_date_num_edit, :citizen_requests if user.rights.include?('citizen_requests_reg_date_num_edit')
        can :show, :citizen_requests_decisions if user.rights.include?('citizen_requests_decisions_show')
        can :index, :citizen_requests_decisions if user.rights.include?('citizen_requests_decisions_index')
        can :edit, :citizen_requests_decisions if user.rights.include?('citizen_requests_decisions_edit')
        can :create, :citizen_requests_decisions if user.rights.include?('citizen_requests_decisions_create')
        can :destroy, :citizen_requests_decisions if user.rights.include?('citizen_requests_decisions_destroy')
        can :create, :citizen_requests if user.rights.include?('citizen_requests_create')
        can :make_links, :citizen_requests if user.rights.include?('citizen_requests_make_links')
        can :cover_letter, :citizen_requests if user.rights.include?('citizen_requests_cover_letter')
        can :notification, :citizen_requests if user.rights.include?('citizen_requests_notification')
        can :approve, :citizen_requests_decisions if user.rights.include?('citizen_requests_approve_decisions')
        can :reg_date_num_print, :citizen_requests if user.rights.include?('citizen_requests_reg_date_num_print')
        can :citizen_create, :citizen_requests if user.rights.include?('citizen_requests_citizen_create')
        can :organization_create, :citizen_requests if user.rights.include?('citizen_requests_organization_create')
        can :check_by_address, :citizen_requests if user.rights.include?('citizen_requests_check_by_address')
        can :check_by_address_with_union, :citizen_requests if user.rights.include?('citizen_requests_check_by_address_with_union')
        can :check_by_lastname, :citizen_requests if user.rights.include?('citizen_requests_check_by_lastname')
        can :check_by_lastname_with_union, :citizen_requests if user.rights.include?('citizen_requests_check_by_lastname_with_union')
        can :destroy_union, :citizen_requests if user.rights.include?('citizen_requests_destroy_union')
        can :chat_show, :citizen_requests if user.rights.include?('citizen_requests_chat_show')
        can :char_edit, :citizen_requests if user.rights.include?('citizen_requests_char_edit')
        can :change_deadline, :citizen_requests if user.rights.include?('citizen_requests_change_deadline')
        can :answer, :citizen_requests if user.rights.include?('citizen_requests_answer')
        can :chat, :citizen_requests if user.rights.include?('citizen_requests_chat')
        can :statistics, :citizen_requests if user.rights.include?('citizen_requests_statistics')
        can :show, :citizen_requests_document_images if user.rights.include?('citizen_requests_document_images_show')
        can :index, :citizen_requests_document_images if user.rights.include?('citizen_requests_document_images_index')
        can :edit, :citizen_requests_document_images if user.rights.include?('citizen_requests_document_images_edit')
        can :create, :citizen_requests_document_images if user.rights.include?('citizen_requests_document_images_create')
        can :destroy, :citizen_requests_document_images if user.rights.include?('citizen_requests_document_images_destroy')

        can :from_report, :secret_orders if user.rights.include?('secret_orders_from_report')
        can :return_from_familiarization, :secret_orders if user.rights.include?('secret_orders_return_from_familiarization')
        can :from_copy, :secret_orders if user.rights.include?('secret_orders_from_copy')
        can :issuance_by_book, :secret_orders if user.rights.include?('secret_orders_issuance_by_book')
        can :addition, :secret_orders if user.rights.include?('secret_orders_addition')
        can :close_cusp, :secret_orders if user.rights.include?('secret_orders_close_cusp')
        can :to_the_file_edit, :secret_orders if user.rights.include?('secret_orders_to_the_file_edit')
        can :notification_card, :secret_orders_control if user.rights.include?('secret_orders_control_notification_card')
        can :control_form, :secret_orders_control if user.rights.include?('secret_orders_control_control_form')
        can :control_form_edit, :secret_orders_control if user.rights.include?('secret_orders_control_control_form_edit')
        can :control_form_print, :secret_orders_control if user.rights.include?('secret_orders_control_control_form_print')
        can :info_card_print, :secret_orders_control if user.rights.include?('secret_orders_control_info_card_print')
        can :on_control, :secret_orders_control if user.rights.include?('secret_orders_control_on_control')
        can :from_control, :secret_orders_control if user.rights.include?('secret_orders_control_from_control')
        can :to_familiarization, :secret_orders if user.rights.include?('secret_orders_to_familiarization')
        can :registration_reminder, :secret_orders if user.rights.include?('secret_orders_registration_reminder')
        can :cancel, :secret_orders if user.rights.include?('secret_orders_cancel')
        can :transfer, :secret_orders if user.rights.include?('secret_orders_transfer')
        can :print_to_the_copy, :secret_orders if user.rights.include?('secret_orders_print_to_the_copy')
        can :print, :secret_orders_decisions if user.rights.include?('secret_orders_print_decisions')
        can :print_search_results, :secret_orders if user.rights.include?('secret_orders_print_search_results')
        can :sign, :secret_orders_decisions if user.rights.include?('secret_orders_sign_decisions')
        can :to_the_file, :secret_orders if user.rights.include?('secret_orders_to_the_file')
        can :stream_scan, :secret_orders if user.rights.include?('secret_orders_stream_scan')
        can :check_existance_medo, :secret_orders if user.rights.include?('secret_orders_check_existance_medo')
        can :check_repeat, :secret_orders if user.rights.include?('secret_orders_check_repeat')
        can :show, :secret_orders if user.rights.include?('secret_orders_show')
        can :index, :secret_orders if user.rights.include?('secret_orders_index')
        can :grouped_docs_work, :secret_orders if user.rights.include?('secret_orders_grouped_docs_work')
        can :distribution, :secret_orders if user.rights.include?('secret_orders_distribution')
        can :distribution_show, :secret_orders if user.rights.include?('secret_orders_distribution_show')
        can :search, :secret_orders if user.rights.include?('secret_orders_advanced_search')
        can :edit, :secret_orders if user.rights.include?('secret_orders_edit')
        can :reg_date_num_edit, :secret_orders if user.rights.include?('secret_orders_reg_date_num_edit')
        can :show, :secret_orders_decisions if user.rights.include?('secret_orders_decisions_show')
        can :index, :secret_orders_decisions if user.rights.include?('secret_orders_decisions_index')
        can :edit, :secret_orders_decisions if user.rights.include?('secret_orders_decisions_edit')
        can :create, :secret_orders_decisions if user.rights.include?('secret_orders_decisions_create')
        can :destroy, :secret_orders_decisions if user.rights.include?('secret_orders_decisions_destroy')
        can :create, :secret_orders if user.rights.include?('secret_orders_create')
        can :make_links, :secret_orders if user.rights.include?('secret_orders_make_links')
        can :approve, :secret_orders_decisions if user.rights.include?('secret_orders_approve_decisions')
        can :show, :secret_orders_document_images if user.rights.include?('secret_orders_document_images_show')
        can :index, :secret_orders_document_images if user.rights.include?('secret_orders_document_images_index')
        can :edit, :secret_orders_document_images if user.rights.include?('secret_orders_document_images_edit')
        can :create, :secret_orders_document_images if user.rights.include?('secret_orders_document_images_create')
        can :destroy, :secret_orders_document_images if user.rights.include?('secret_orders_document_images_destroy')

        can :from_report, :orders if user.rights.include?('orders_from_report')
        can :return_from_familiarization, :orders if user.rights.include?('orders_return_from_familiarization')
        can :from_copy, :orders if user.rights.include?('orders_from_copy')
        can :issuance_by_book, :orders if user.rights.include?('orders_issuance_by_book')
        can :addition, :orders if user.rights.include?('orders_addition')
        can :close_cusp, :orders if user.rights.include?('orders_close_cusp')
        can :to_the_file_edit, :orders if user.rights.include?('orders_to_the_file_edit')
        can :notification_card, :orders_control if user.rights.include?('orders_control_notification_card')
        can :control_form, :orders_control if user.rights.include?('orders_control_control_form')
        can :control_form_edit, :orders_control if user.rights.include?('orders_control_control_form_edit')
        can :control_form_print, :orders_control if user.rights.include?('orders_control_control_form_print')
        can :info_card_print, :orders_control if user.rights.include?('orders_control_info_card_print')
        can :on_control, :orders_control if user.rights.include?('orders_control_on_control')
        can :from_control, :orders_control if user.rights.include?('orders_control_from_control')
        can :to_familiarization, :orders if user.rights.include?('orders_to_familiarization')
        can :registration_reminder, :orders if user.rights.include?('orders_registration_reminder')
        can :cancel, :orders if user.rights.include?('orders_cancel')
        can :view_gov_registration, :orders if user.rights.include?('orders_view_gov_registration')
        can :view_cause_block, :orders if user.rights.include?('orders_view_cause_block')
        can :view_declared_document_type, :orders if user.rights.include?('orders_view_declared_document_type')
        can :view_passage_history, :orders if user.rights.include?('orders_view_passage_history')
        can :transfer, :orders if user.rights.include?('orders_transfer')
        can :print_to_the_copy, :orders if user.rights.include?('orders_print_to_the_copy')
        can :print, :orders_decisions if user.rights.include?('orders_print_decisions')
        can :print_search_results, :orders if user.rights.include?('orders_print_search_results')
        can :sign, :orders_decisions if user.rights.include?('orders_sign_decisions')
        can :to_the_file, :orders if user.rights.include?('orders_to_the_file')
        can :stream_scan, :orders if user.rights.include?('orders_stream_scan')
        can :check_existance_medo, :orders if user.rights.include?('orders_check_existance_medo')
        can :check_repeat, :orders if user.rights.include?('orders_check_repeat')
        can :show, :orders if user.rights.include?('orders_show')
        can :index, :orders if user.rights.include?('orders_index')
        can :grouped_docs_work, :orders if user.rights.include?('orders_grouped_docs_work')
        can :distribution, :orders if user.rights.include?('orders_distribution')
        can :distribution_show, :orders if user.rights.include?('orders_distribution_show')
        can :search, :orders if user.rights.include?('orders_advanced_search')
        can :edit, :orders if user.rights.include?('orders_edit')
        can :reg_date_num_edit, :orders if user.rights.include?('orders_reg_date_num_edit')
        can :show, :orders_decisions if user.rights.include?('orders_decisions_show')
        can :index, :orders_decisions if user.rights.include?('orders_decisions_index')
        can :edit, :orders_decisions if user.rights.include?('orders_decisions_edit')
        can :create, :orders_decisions if user.rights.include?('orders_decisions_create')
        can :destroy, :orders_decisions if user.rights.include?('orders_decisions_destroy')
        can :create, :orders if user.rights.include?('orders_create')
        can :make_links, :orders if user.rights.include?('orders_make_links')
        can :approve, :orders_decisions if user.rights.include?('orders_approve_decisions')
        can :show, :orders_document_images if user.rights.include?('orders_document_images_show')
        can :index, :orders_document_images if user.rights.include?('orders_document_images_index')
        can :edit, :orders_document_images if user.rights.include?('orders_document_images_edit')
        can :create, :orders_document_images if user.rights.include?('orders_document_images_create')
        can :destroy, :orders_document_images if user.rights.include?('orders_document_images_destroy')

        can :view_passage_history, :orders if user.rights.include?('orders_view_passage_history')

        can :from_report, :orders_ddo if user.rights.include?('orders_ddo_from_report')
        can :return_from_familiarization, :orders_ddo if user.rights.include?('orders_ddo_return_from_familiarization')
        can :from_copy, :orders_ddo if user.rights.include?('orders_ddo_from_copy')
        can :addition, :orders_ddo if user.rights.include?('orders_ddo_addition')
        can :close_cusp, :orders_ddo if user.rights.include?('orders_ddo_close_cusp')
        can :to_the_file_edit, :orders_ddo if user.rights.include?('orders_ddo_to_the_file_edit')
        can :notification_card, :orders_ddo_control if user.rights.include?('orders_ddo_control_notification_card')
        can :control_form, :orders_ddo_control if user.rights.include?('orders_ddo_control_control_form')
        can :control_form_edit, :orders_ddo_control if user.rights.include?('orders_ddo_control_control_form_edit')
        can :control_form_print, :orders_ddo_control if user.rights.include?('orders_ddo_control_control_form_print')
        can :info_card_print, :orders_ddo_control if user.rights.include?('orders_ddo_control_info_card_print')
        can :on_control, :orders_ddo_control if user.rights.include?('orders_ddo_control_on_control')
        can :from_control, :orders_ddo_control if user.rights.include?('orders_ddo_control_from_control')
        can :to_familiarization, :orders_ddo if user.rights.include?('orders_ddo_to_familiarization')
        can :registration_reminder, :orders_ddo if user.rights.include?('orders_ddo_registration_reminder')
        can :cancel, :orders_ddo if user.rights.include?('orders_ddo_cancel')
        can :view_gov_registration, :orders_ddo if user.rights.include?('orders_ddo_view_gov_registration')
        can :view_cause_block, :orders_ddo if user.rights.include?('orders_ddo_view_cause_block')
        can :view_declared_document_type, :orders_ddo if user.rights.include?('orders_ddo_view_declared_document_type')
        can :view_passage_history, :orders_ddo if user.rights.include?('orders_ddo_view_passage_history')
        can :transfer, :orders_ddo if user.rights.include?('orders_ddo_transfer')
        can :print_to_the_copy, :orders_ddo if user.rights.include?('orders_ddo_print_to_the_copy')
        can :print, :orders_ddo_decisions if user.rights.include?('orders_ddo_print_decisions')
        can :print_search_results, :orders_ddo if user.rights.include?('orders_ddo_print_search_results')
        can :sign, :orders_ddo_decisions if user.rights.include?('orders_ddo_sign_decisions')
        can :to_the_file, :orders_ddo if user.rights.include?('orders_ddo_to_the_file')
        can :stream_scan, :orders_ddo if user.rights.include?('orders_ddo_stream_scan')
        can :check_existance_medo, :orders_ddo if user.rights.include?('orders_ddo_check_existance_medo')
        can :check_repeat, :orders_ddo if user.rights.include?('orders_ddo_check_repeat')
        can :show, :orders_ddo if user.rights.include?('orders_ddo_show')
        can :index, :orders_ddo if user.rights.include?('orders_ddo_index')
        can :grouped_docs_work, :orders_ddo if user.rights.include?('orders_ddo_grouped_docs_work')
        can :distribution, :orders_ddo if user.rights.include?('orders_ddo_distribution')
        can :distribution_show, :orders_ddo if user.rights.include?('orders_ddo_distribution_show')
        can :search, :orders_ddo if user.rights.include?('orders_ddo_advanced_search')
        can :edit, :orders_ddo if user.rights.include?('orders_ddo_edit')
        can :reg_date_num_edit, :orders_ddo if user.rights.include?('orders_ddo_reg_date_num_edit')
        can :show, :orders_ddo_decisions if user.rights.include?('orders_ddo_decisions_show')
        can :index, :orders_ddo_decisions if user.rights.include?('orders_ddo_decisions_index')
        can :edit, :orders_ddo_decisions if user.rights.include?('orders_ddo_decisions_edit')
        can :create, :orders_ddo_decisions if user.rights.include?('orders_ddo_decisions_create')
        can :destroy, :orders_ddo_decisions if user.rights.include?('orders_ddo_decisions_destroy')
        can :create, :orders_ddo if user.rights.include?('orders_ddo_create')
        can :make_links, :orders_ddo if user.rights.include?('orders_ddo_make_links')
        can :approve, :orders_ddo_decisions if user.rights.include?('orders_ddo_approve_decisions')
        can :show, :orders_ddo_document_images if user.rights.include?('orders_ddo_document_images_show')
        can :index, :orders_ddo_document_images if user.rights.include?('orders_ddo_document_images_index')
        can :edit, :orders_ddo_document_images if user.rights.include?('orders_ddo_document_images_edit')
        can :create, :orders_ddo_document_images if user.rights.include?('orders_ddo_document_images_create')
        can :destroy, :orders_ddo_document_images if user.rights.include?('orders_ddo_document_images_destroy')

        can :view_passage_history, :orders_ddo if user.rights.include?('orders_ddo_view_passage_history')
        can :view_delete_all_button, :orders_ddo if user.rights.include?('orders_ddo_view_delete_all_button')

        can :show, :permissions_users_groups if user.rights.include?('permissions_users_groups_show')
        can :index, :permissions_users_groups if user.rights.include?('permissions_users_groups_index')
        can :edit, :permissions_users_groups if user.rights.include?('permissions_users_groups_edit')
        can :create, :permissions_users_groups if user.rights.include?('permissions_users_groups_create')
        can :destroy, :permissions_users_groups if user.rights.include?('permissions_users_groups_destroy')
        can :show, :permissions_users if user.rights.include?('permissions_users_show')
        can :index, :permissions_users if user.rights.include?('permissions_users_index')
        can :edit, :permissions_users if user.rights.include?('permissions_users_edit')
        can :create, :permissions_users if user.rights.include?('permissions_users_create')
        can :destroy, :permissions_users if user.rights.include?('permissions_users_destroy')
        can :show, :permissions_roles if user.rights.include?('permissions_roles_show')
        can :index, :permissions_roles if user.rights.include?('permissions_roles_index')
        can :edit, :permissions_roles if user.rights.include?('permissions_roles_edit')
        can :create, :permissions_roles if user.rights.include?('permissions_roles_create')
        can :destroy, :permissions_roles if user.rights.include?('permissions_roles_destroy')

        can :show, :registers_npa_registers if user.rights.include?('registers_npa_registers_show')
        can :index, :registers_npa_registers if user.rights.include?('registers_npa_registers_index')
        can :edit, :registers_npa_registers if user.rights.include?('registers_npa_registers_edit')
        can :create, :registers_npa_registers if user.rights.include?('registers_npa_registers_create')
        can :destroy, :registers_npa_registers if user.rights.include?('registers_npa_registers_destroy')

        can :access, :registers_register if user.rights.include?('registers_register_access')
        can :show, :registers_register_items if user.rights.include?('registers_register_items_show')
        can :index, :registers_register_items if user.rights.include?('registers_register_items_index')
        can :edit, :registers_register_items if user.rights.include?('registers_register_items_edit')
        can :create, :registers_register_items if user.rights.include?('registers_register_items_create')
        can :destroy, :registers_register_items if user.rights.include?('registers_register_items_destroy')

        can :access, :registers_ddo_type if user.rights.include?('registers_ddo_type_access')
        can :access, :registers_primary_consideration if user.rights.include?('registers_primary_consideration_access')
        can :access, :registers_reg_group_to_send_group if user.rights.include?('registers_reg_group_to_send_group_access')
        can :access, :registers_reg_group_to_citizen_requests_group if user.rights.include?('registers_reg_group_to_citizen_requests_group_access')
        can :access, :registers_reg_group_to_oper_group if user.rights.include?('registers_reg_group_to_oper_group_access')
        can :access, :registers_oper_group_to_send_group if user.rights.include?('registers_oper_group_to_send_group_access')
        can :access, :registers_to_the_file if user.rights.include?('registers_to_the_file_access')


        can :show, :classifiers_assistants if user.rights.include?('classifiers_assistants_show')
        can :index, :classifiers_assistants if user.rights.include?('classifiers_assistants_index')
        can :edit, :classifiers_assistants if user.rights.include?('classifiers_assistants_edit')
        can :create, :classifiers_assistants if user.rights.include?('classifiers_assistants_create')
        can :destroy, :classifiers_assistants if user.rights.include?('classifiers_assistants_destroy')
        can :show, :classifiers_portfolios if user.rights.include?('classifiers_portfolios_show')
        can :index, :classifiers_portfolios if user.rights.include?('classifiers_portfolios_index')
        can :edit, :classifiers_portfolios if user.rights.include?('classifiers_portfolios_edit')
        can :create, :classifiers_portfolios if user.rights.include?('classifiers_portfolios_create')
        can :destroy, :classifiers_portfolios if user.rights.include?('classifiers_portfolios_destroy')
        can :show, :classifiers_reasons if user.rights.include?('classifiers_reasons_show')
        can :index, :classifiers_reasons if user.rights.include?('classifiers_reasons_index')
        can :edit, :classifiers_reasons if user.rights.include?('classifiers_reasons_edit')
        can :create, :classifiers_reasons if user.rights.include?('classifiers_reasons_create')
        can :destroy, :classifiers_reasons if user.rights.include?('classifiers_reasons_destroy')
        can :show, :classifiers_themes if user.rights.include?('classifiers_themes_show')
        can :index, :classifiers_themes if user.rights.include?('classifiers_themes_index')
        can :edit, :classifiers_themes if user.rights.include?('classifiers_themes_edit')
        can :create, :classifiers_themes if user.rights.include?('classifiers_themes_create')
        can :destroy, :classifiers_themes if user.rights.include?('classifiers_themes_destroy')
        can :show, :classifiers_control_types if user.rights.include?('classifiers_control_types_show')
        can :index, :classifiers_control_types if user.rights.include?('classifiers_control_types_index')
        can :edit, :classifiers_control_types if user.rights.include?('classifiers_control_types_edit')
        can :create, :classifiers_control_types if user.rights.include?('classifiers_control_types_create')
        can :destroy, :classifiers_control_types if user.rights.include?('classifiers_control_types_destroy')
        can :show, :classifiers_order_ddo_types if user.rights.include?('classifiers_order_ddo_types_show')
        can :index, :classifiers_order_ddo_types if user.rights.include?('classifiers_order_ddo_types_index')
        can :edit, :classifiers_order_ddo_types if user.rights.include?('classifiers_order_ddo_types_edit')
        can :create, :classifiers_order_ddo_types if user.rights.include?('classifiers_order_ddo_types_create')
        can :destroy, :classifiers_order_ddo_types if user.rights.include?('classifiers_order_ddo_types_destroy')
        can :show, :classifiers_order_types if user.rights.include?('classifiers_order_types_show')
        can :index, :classifiers_order_types if user.rights.include?('classifiers_order_types_index')
        can :edit, :classifiers_order_types if user.rights.include?('classifiers_order_types_edit')
        can :create, :classifiers_order_types if user.rights.include?('classifiers_order_types_create')
        can :destroy, :classifiers_order_types if user.rights.include?('classifiers_order_types_destroy')
        can :show, :classifiers_change_types if user.rights.include?('classifiers_change_types_show')
        can :index, :classifiers_change_types if user.rights.include?('classifiers_change_types_index')
        can :edit, :classifiers_change_types if user.rights.include?('classifiers_change_types_edit')
        can :create, :classifiers_change_types if user.rights.include?('classifiers_change_types_create')
        can :destroy, :classifiers_change_types if user.rights.include?('classifiers_change_types_destroy')
        can :show, :classifiers_simples if user.rights.include?('classifiers_simples_show')
        can :index, :classifiers_simples if user.rights.include?('classifiers_simples_index')
        can :edit, :classifiers_simples if user.rights.include?('classifiers_simples_edit')
        can :create, :classifiers_simples if user.rights.include?('classifiers_simples_create')
        can :destroy, :classifiers_simples if user.rights.include?('classifiers_simples_destroy')
        can :show, :classifiers_jurists if user.rights.include?('classifiers_jurists_show')
        can :index, :classifiers_jurists if user.rights.include?('classifiers_jurists_index')
        can :edit, :classifiers_jurists if user.rights.include?('classifiers_jurists_edit')
        can :create, :classifiers_jurists if user.rights.include?('classifiers_jurists_create')
        can :destroy, :classifiers_jurists if user.rights.include?('classifiers_jurists_destroy')
        can :show, :classifiers_importances if user.rights.include?('classifiers_importances_show')
        can :index, :classifiers_importances if user.rights.include?('classifiers_importances_index')
        can :edit, :classifiers_importances if user.rights.include?('classifiers_importances_edit')
        can :create, :classifiers_importances if user.rights.include?('classifiers_importances_create')
        can :destroy, :classifiers_importances if user.rights.include?('classifiers_importances_destroy')

        can :access, :reports_document_execution_control if user.rights.include?('reports_document_execution_control_access')
        can :access, :reports_performing_discipline if user.rights.include?('reports_performing_discipline_access')
        can :access, :reports_sed_info if user.rights.include?('reports_sed_info_access')
        can :access, :reports_sed_status if user.rights.include?('reports_sed_status_access')
        can :access, :reports_citizen_requests_consideration_mvd if user.rights.include?('reports_citizen_requests_consideration_mvd_access')
        can :access, :reports_citizen_requests_from_ap if user.rights.include?('reports_citizen_requests_from_ap_access')
        can :access, :reports_personally_citizen_reception if user.rights.include?('reports_personally_citizen_reception_access')
        can :access, :reports_reg_numbers_for_orders if user.rights.include?('reports_reg_numbers_for_orders_access')
        can :access, :reports_statistical_data_for_orders if user.rights.include?('reports_statistical_data_for_orders_access')
        can :access, :reports_orders_statistics if user.rights.include?('reports_orders_statistics_access')


        can :access, :journals if (
          can?(:index, :incoming_documents) ||
          can?(:index, :outgoing_documents) ||
          can?(:index, :orders) ||
          can?(:index, :incoming_orders) ||
          can?(:index, :citizen_requests) ||
          can?(:index, :secret_incoming_documents) ||
          can?(:index, :secret_outgoing_documents) ||
          can?(:index, :attorney_letters) ||
          can?(:index, :secret_orders) ||
          can?(:index, :secret_incoming_orders) ||
          can?(:index, :orders_ddo)
        )

        can :access, :incoming_documents_operations if can?(:from_copy, :incoming_documents) || can?(:from_report, :incoming_documents) || can?(:stream_scan, :incoming_documents)
        can :access, :outgoing_documents_operations if can?(:from_copy, :outgoing_documents) || can?(:from_report, :outgoing_documents) || can?(:stream_scan, :outgoing_documents)
        can :access, :orders_operations if can?(:from_copy, :orders) || can?(:from_report, :orders) || can?(:stream_scan, :orders)
        can :access, :incoming_orders_operations if can?(:from_copy, :incoming_orders) || can?(:from_report, :incoming_orders) || can?(:stream_scan, :incoming_orders)

        can :access, :secret_incoming_documents_operations if can?(:from_copy, :secret_incoming_documents) || can?(:from_report, :secret_incoming_documents) || can?(:stream_scan, :secret_incoming_documents)
        can :access, :secret_outgoing_documents_operations if can?(:from_copy, :secret_outgoing_documents) || can?(:from_report, :secret_outgoing_documents) || can?(:stream_scan, :secret_outgoing_documents)
        can :access, :attorney_letters_operations if can?(:from_copy, :attorney_letters) || can?(:from_report, :attorney_letters) || can?(:stream_scan, :attorney_letters)
        can :access, :secret_orders_operations if can?(:from_copy, :secret_orders) || can?(:from_report, :secret_orders) || can?(:stream_scan, :secret_orders)
        can :access, :secret_incoming_orders_operations if can?(:from_copy, :secret_incoming_orders) || can?(:from_report, :secret_incoming_orders) || can?(:stream_scan, :secret_incoming_orders)

        can :access, :orders_ddo_operations if can?(:from_copy, :orders_ddo) || can?(:from_report, :orders_ddo) || can?(:stream_scan, :orders_ddo)

        can :access, :citizen_requests_operations if can?(:from_copy, :citizen_requests) || can?(:from_report, :citizen_requests) || can?(:stream_scan, :citizen_requests)

        can :access, :control if !(user.rights.select { |right| right =~ /^control/ }.count.zero?)
        can :access, :registers_register if user.rights.include?('registers_register_access')
        can :access, :classifiers unless user.rights.select { |right| right =~ /^classifiers|oshs/ }.count.zero?
        can :access, :settings unless user.rights.select { |right| right =~ /^settings|permissions/ }.count.zero?
        can :access, :logs if can?(:access, :logs_logs) || can?(:access, :logs_changes)
        can :access, :registers if can?(:access, :registers_register) || can?(:index, :registers_register_items) || can?(:index, :registers_npa_registers)
        can :access, :reports unless user.rights.select { |right| right =~ /^reports/ }.count.zero?


      end

    end
  end
end
